BLUEAXI4DIR ?= $(CURDIR)/BlueAXI4
BLUEUNIXBRIDGESDIR = $(BLUEAXI4DIR)/BlueUnixBridges
include $(BLUEUNIXBRIDGESDIR)/blueunixbridges.inc.mk
BLUEAXI4_DIRS = $(BLUEAXI4DIR):$(BLUEAXI4DIR)/AXI4:$(BLUEAXI4DIR)/AXI4Lite:$(BLUEAXI4DIR)/AXI4Stream:$(BLUEUNIXBRIDGES_DIRS)
